### ISSUE TITLE
Kondordancia

### ISSUE THREAD

**Issue by gyuris** [briff/ujszov.szentiras.hu#42]
Úgy látom, hogy egy ideje már nem töltődnek be a konkordanciák.

Pl: a https://ujszov.hu/text/concordance/206001016000050/2 "500 Internal Server Error"-ral elszáll.

**Comment by Csomorkany** [comment]
Köszönöm a jelzést, röviden: hát igen. A programozóm túl régen nem
foglalkozott a projekttel, és most építi újra a fejlesztői környezetet.
Szóval tudunk a problémáról, de gyors megoldást nem tudok ígérni :-(

Gyuris Gellért ***@***.***> ezt írta (időpont: 2022. okt.
30., V, 1:03):
